### ISSUE TITLE
Web Application is un-testable 

### ISSUE THREAD

**Issue by donaldp** [formidablejs/framework#48]
### Details

`supertest` request throws error 500 when the application uses Imba views.

### Expected Behavior

Default test should always return a status code of 200.

### Actual Behavior

Test throws error 500.

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Node.js 14.18.1:
- Linux 5.3.0-62-generic:
- Useful link to screenshot or any other information:

### Steps to Reproduce

1. create new formidable application using `craftsman new <name> --web`
2. change `environment` to `testing` in the `.env`
3. run `craftsman build`
4. run `npm run test`

### Stack Trace

```
TypeError: Cannot read property 'inputs' of undefined
    at $r.inputs [as get] (/home/donald/code/myapp/.formidable/server.app.js:2:9929)
    at at.input (/home/donald/code/myapp/.formidable/server.app.js:2:10278)
    at at.asset (/home/donald/code/myapp/.formidable/server.app.js:2:10352)
    at at.String [as get] (/home/donald/code/myapp/.formidable/server.app.js:2:10479)
    at String (<anonymous>)
    at ys.outerHTML (/home/donald/code/myapp/.formidable/server.app.js:5:915)
    at r.innerHTML (/home/donald/code/myapp/.formidable/server.app.js:2:29957)
    at r.outerHTML (/home/donald/code/myapp/.formidable/server.app.js:2:30401)
    at cs.innerHTML (/home/donald/code/myapp/.formidable/server.app.js:2:29957)
    at cs.outerHTML (/home/donald/code/myapp/.formidable/server.app.js:2:30401)
    at cs.outerHTML (/home/donald/code/myapp/.formidable/server.app.js:2:32119)
    at cs.toString (/home/donald/code/myapp/.formidable/server.app.js:2:26360)
    at String (<anonymous>)
    at er.make (/home/donald/code/myapp/node_modules/@formidablejs/framework/lib/Http/View/View.js:101:10)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at ViewResponse.toView (/home/donald/code/myapp/node_modules/@formidablejs/framework/lib/Http/Response/ViewResponse.js:47:18)


```
</details>

**Comment by donaldp** [comment]
Working fix:
https://github.com/formidablejs/framework/tree/feature/craftsman
https://github.com/formidablejs/formidablejs/tree/feature/craftsman

**Comment by donaldp** [comment]
This doesn't seem to be an issue anymore.

Scaffolding an MPA Imba app with Auth and running the following test, seems to work:

```ts
const formidable = require('../.formidable/build').default
const supertest = require('supertest')

describe('Application (e2e)', () => {
	let app

	beforeAll(async () => {
		const application = await formidable

		app = application.fastify()

		await app.ready()
	})

	afterAll(async () => {
		await app.close()
	})

	it('/ (GET: Welcome)', async () => {
		await supertest(app.server)
			.get('/')
			.expect(200)
			.expect('Content-Type', 'text/html')
			.expect((res) => {
				expect(res.text).toContain('Your app is ready with Auth scaffolding')
			})
	})
})
```

This means, we just need to update the boiler tests

**Comment by donaldp** [comment]
Fixed in https://github.com/formidablejs/view/pull/66
